### PR TITLE
Use dh_auto_test for testing

### PR DESCRIPTION
**Pull request by krnowak**
It should be clever enough to call make check, but it also respects
the DEB_BUILD_OPTIONS environment variable, so I can skip the tests
when doing scratch builds on my computer.

### CODE REVIEW

**Comment by dbnicholson** [comment]
Isn't this handled by `override_dh_auto_test` in `debian/rules`?

**Comment by dbnicholson** [comment]
Or maybe that override needs to handle the option manually. I think that would be the more appropriate place to make any changes.

**Comment by krnowak** [comment]
Alright, will update it tomorrow.

**Comment by dbnicholson** [comment]
Bonus points if you file upstream in Debian. We follow the upstream packaging pretty closely and Simon McVittie is pretty responsive.

**Comment by krnowak** [comment]
Alright, filed - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=862803

**Comment by dbnicholson** [comment]
Thanks, that looks good except for `s/ifeq/ifneq/` (comment should be coming to the Debian BTS soon). We can apply that locally if you want, too, but I'd like to wait a day to see if Simon responds.

**Comment by krnowak** [comment]
I actually think `ifeq` is correct. :P The reasoning should be on the BTS shortly.

Anyway, no need to hurry with applying that locally - I just patched that thing myself and I'm fine.

**Comment by dbnicholson** [comment]
Oh, right! You're using the conditional to say "yes, run the tests". This should only be done if `nocheck` is _not_ in `DEB_BUILD_OPTIONS`.

**Comment by krnowak** [comment]
I'm closing it - the (different) fix I have made for upstream was just recently ported to debian-master branch.

**Pull request closed without merging**
