### PR TITLE
Rebase on debian 2022.1-3

### PR DESCRIPTION
**Pull request by dbnicholson**
This is a rebase on top of debian's 2022.1-3 package. Here's a list of our patches on top of our previous 2020.8-2 base:

- [x] 80cbe1cd Remove grub2 files from ostree-boot package

Ensures that our `grub.cfg` won't be updated if the deploy code gets to that point. In #186 I left some notes about reliably ensuring that the `bootloader=none` case is always taken. For now I think we should keep this.

- [ ] 2db10b2b Revert "Temporarily disable gjs tests"

Re-enabled in by debian 2021.3-1.

- [ ] d6102321 Bring back trivial-httpd subcommand

Reverted later since eos-updater no longer relies on it.

- [x] cd33889e debian: Document Endless packaging changes
- [x] 3f1fc48d Remove debian/patches

Not much to say here. Updated the packaging changes to remove the `gjs` delta and mention the FUSE 2 v 3 delta (see below).

- [ ] 4c6f5c73 Release 2020.8-2endless1

Old changelog entry.

- [ ] 7376aed3 Revert "Bring back trivial-httpd subcommand"
- [ ] 1d7aaa6c d/README.Endless: Remove trivial-httpd delta

See above.

- [ ] 6102bb40 d/libostree-1-1.symbols: Add backported repo locking symbols
- [ ] 7e951c74 d/control: Bump glib build dep to 2.44.0

Upstream backports.

The only other change has to do with FUSE and flatpak-builder. flatpak-builder uses ostree's `rofiles-fuse` filesystem. Recently `rofiles-fuse` was changed to build using either FUSE 2 or FUSE 3 and debian changed their build to use FUSE 3. We're still using bullseye's flatpak-builder 1.0.12, which tries to use FUSE 2 only options with `rofiles-fuse`. So, for now I reverted the commits to build against FUSE 3 and declare `Breaks: flatpak-builder (<< 1.2.1-2~)`.

I think when I go to update flatpak to 1.12 I'll likely pull in flatpak-builder from testing so they stay in sync. But I can't do it the other way around since flatpak-builder 1.2 depends on flatpak 1.12.

The post-rebase queue can be seen in https://github.com/endlessm/ostree/compare/Version_2022.1_debian...T32964-rebase-2022.1-3. The master PR is in #186.

https://phabricator.endlessm.com/T32964

### CODE REVIEW

**Comment by wjt** [comment]
retest this please, Jenkins!

**Review by pwithnall — APPROVED** [review]
LGTM. CI is failing but that looks like a missing tag:

```
+ dch -v 2020.8+dev24.c6a1f7e-457 -D master --force-distribution 'Automatic release from git (2020.8+dev24.c6a1f7e-457)'
dch: fatal error at line 1220:
New version specified (2020.8+dev24.c6a1f7e-457) is less than
the current version number (2022.1-3endless1)!  Use -b to force.
```

**Comment by pwithnall** [comment]
Looks like the `Version_2022.1_debian` tag is on the upstream Debian packaging release commit, not the downstream Endless packaging release commit

**Comment by dbnicholson** [comment]
retest this please

**Comment by dbnicholson** [comment]
> Looks like the `Version_2022.1_debian` tag is on the upstream Debian packaging release commit, not the downstream Endless packaging release commit

Thanks. I tried to outsmart my own stupid system and lost.

**Comment by dbnicholson** [comment]
Argh. It's trying to use the `master` branch because I named this branch unlike the conventional `T32964-rebase-2022.1-debian` that `jenkins-obs-pr` is expecting. Similarly, #186 is using the `debian-master` branch. I'm going to have to close this and move to a different branch.

**Pull request closed without merging**
